
import torch
from pathlib import Path

# Global Vars
DEVICE_ACCELERATION = torch.device("cuda")
TRAINING_DATA_DIR = Path("./data")
GRID_HW = 32
N_ROOM_TYPES = 10
MAX_VERTICES = 16

# VAE Vars
VAE_N_EPOCHS = 2000
VAE_TRAIN_PCT = 0.95
VAE_BATCH_SIZE = 8
VAE_HIDDEN_DIM = 1024
VAE_N_CHANNELS = 6
VAE_CODEBOOK_DIM = 512
VAE_CODEBOOK_TOKENS_VOCAB_SIZE = 1024

VAE_SMOOTH_L1_LOSS = False
VAE_N_RESNET_BLOCKS = 2
VAE_N_LAYERS = 2
VAE_STRAIGHT_THROUGH = False
VAE_REINMAX = False
VAE_LEARNING_RATE = 1e-4
VAE_TEMP_STARTING_VALUE = 1.0
VAE_TEMP_ANNEALING_RATE = 1e-6
VAE_KL_DIV_LOSS_WEIGHT = 0.0
VAE_SAVE_PATH = Path("trained_vae.pt")

# GCN Varsc
GCN_N_NODE_FEATURES = 3
GCN_N_LAYERS = 2
GCN_LAYER_HIDDEN_DIM = 32
GCN_DROPOUT_PCT = 0.0

# Transformer Vars
TF_N_EPOCHS = 2000
TF_TRAIN_PCT = 1.0
TF_BATCH_SIZE = 512
TF_MODEL_DIMS = 256
TF_N_ENC_DEC_HEADS = 8
TF_N_LAYERS = 6
TF_FF_DIMS = 2048
TF_DROPOUT = 0.0
TF_LEARNING_RATE = 1e-5

META_MODEL_SAVE_PATH = Path("trained_metamodel.pt")
