[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dallg"
description = ""
requires-python = ">=3.8"
version = "0.0.1"

[project.optional-dependencies]
dev = ["pytest"]
